name: Build Executable and Publish Release

on:
  push:
    branches:
      - main

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install pyinstaller
        run: |
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile main.py
          mv dist/main dist/Lesta_Cluster_Selector
          chmod +x dist/Lesta_Cluster_Selector

      - name: Create zip archive
        run: zip -j Lesta_Cluster_Selector.zip dist/Lesta_Cluster_Selector

      - name: Upload zip archive as artifact
        uses: actions/upload-artifact@v2
        with:
          name: macos-executable
          path: Lesta_Cluster_Selector.zip

  build-windows:
    runs-on: windows-latest
    needs: build-macos

    steps:
      - name: Download macos-executable artifact
        uses: actions/download-artifact@v2
        with:
          name: macos-executable

      - name: Unzip macos-executable
        run: Expand-Archive -Path macos-executable.zip -DestinationPath macos-executable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install pyinstaller
        run: |
          pip install pyinstaller

      - name: Build Windows executable
        run: |
          pyinstaller --onefile main.py
          mv dist/main.exe dist/Lesta_Cluster_Selector.exe

      - name: Create Windows zip archive
        run: Compress-Archive -Path dist/Lesta_Cluster_Selector.exe -DestinationPath Lesta_Cluster_Selector_Windows.zip

      - name: Upload Windows Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_PUBLIC }}
        with:
          upload_url: ${{ github.event.inputs.upload_url }}
          asset_path: Lesta_Cluster_Selector_Windows.zip
          asset_name: Lesta_Cluster_Selector_Windows.zip
          asset_content_type: application/zip
